name: build GraalVM native image
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  build-native:
    name: 'Build GraalVM Native Image ${{ matrix.platform}}'
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
    runs-on: ${{matrix.os}}
    permissions:
      contents: write
    steps:
      #      - name: linux packages
      #        if: ${{ matrix.os == 'ubuntu-latest' }}
      #        run: |
      #          sudo apt-get update
      #          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Checkout the repository
        uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: '${{ github.token }}'
          cache: maven
      - name: Example step
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
      - name: build by maven
        shell: bash
        run: |
          mvn -Pnative package
          ls ./target
          ./target/graalvm-storage